import { Body, Controller, Post } from '@nestjs/common';
import { ChatService } from './chat.service';
import { SendMessageChatDto } from './dto/send-message-chat.dto';
import { ApiBody, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { AssistantResponseDto, CustomErrorResponseDto } from './dto/assistant-response.dto';

@ApiTags('chat')
@Controller('chat')
export class ChatController {
  constructor(private readonly chatService: ChatService) { }

  @Post()
  @ApiOperation({ summary: 'Send a message to the AI chatbot' })
  @ApiBody({
    description: 'User input message and email address to keep conversation history',
    type: SendMessageChatDto
  })
  @ApiResponse({
    status: 201,
    description: 'The assistant response generated by the LLM',
    type: AssistantResponseDto
  })
  @ApiResponse({
    status: 500,
    description: 'Custom error format returned by the exception filter',
    type: CustomErrorResponseDto
  })
  async postMessage(@Body() payload: SendMessageChatDto) {
    return this.chatService.postMessage(payload)
  }
}
